version: "3"
services:
    chrome:
        image: selenium/standalone-chrome
        networks:
            - image_name_network
    database:
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=laravel
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        image: mysql:latest
        networks:
            - image_name_network
        volumes:
            - database:/var/lib/mysql
    http:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.dev
            args:
                uid: user_id
                gid: group_id
        image: image_name
        ports:
            - "http_port:80"
        networks:
            - image_name_network
        volumes:
            - repo_path:/srv/www
    php:
        image: dlemp-php
        networks:
            - image_name_network
        volumes:
            - repo_path:/srv/www

networks:
    image_name_network:
        driver: bridge

volumes:
    database:
