FROM nginx:alpine

LABEL maintainer="tehtotalpwnage@gmail.com"

ARG gid
ARG uid

# Sets up the server environment.
COPY config/nginx/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /srv/www/

# Run postinstallation scripts.
RUN mkdir -p /srv/logs/

# For security reasons, we want the container to be able to run without root permissions.
RUN addgroup -g $gid dlemp
RUN adduser -D -g '' -G dlemp -u $uid dlemp
RUN chown -R dlemp:dlemp /srv

# The script is still being run as root, but the processes will be under the dlemp user.
USER root:root
